In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("E:\Machine_Learning_Journey\Machine_Learning_Journey\data_sets\social_ads.csv")

In [3]:
data

     Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [5]:
from sklearn.preprocessing import MinMaxScaler

In [6]:
data2 = data.copy()

In [7]:
data2

     Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [8]:
mms = MinMaxScaler()

In [9]:
scaled_all = mms.fit_transform(data2)

In [11]:
data2[:] = scaled_all

In [12]:
data2

          Age  EstimatedSalary  Purchased
0    0.023810         0.029630          0
1    0.404762         0.037037          0
2    0.190476         0.207407          0
3    0.214286         0.311111          0
4    0.023810         0.451852          0
..        ...              ...        ...
395  0.666667         0.192593          1
396  0.785714         0.059259          1
397  0.761905         0.037037          1
398  0.428571         0.133333          0
399  0.738095         0.155556          1

[400 rows x 3 columns]

In [18]:
data3 = data.copy()

In [19]:
data3

     Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [20]:
scaled_salary = mms.fit_transform(data3[['EstimatedSalary']])

In [21]:
scaled_salary

array([[0.02962963],
       [0.03703704],
       [0.20740741],
       [0.31111111],
       [0.45185185],
       [0.31851852],
       [0.51111111],
       [1.        ],
       [0.13333333],
       [0.37037037],
       [0.48148148],
       [0.27407407],
       [0.52592593],
       [0.02222222],
       [0.4962963 ],
       [0.48148148],
       [0.07407407],
       [0.08148148],
       [0.0962963 ],
       [0.1037037 ],
       [0.05185185],
       [0.25185185],
       [0.19259259],
       [0.05185185],
       [0.05925926],
       [0.03703704],
       [0.0962963 ],
       [0.11111111],
       [0.20740741],
       [0.02222222],
       [0.43703704],
       [0.9037037 ],
       [0.00740741],
       [0.21481481],
       [0.55555556],
       [0.08888889],
       [0.0962963 ],
       [0.25185185],
       [0.42222222],
       [0.11851852],
       [0.01481481],
       [0.26666667],
       [0.68888889],
       [0.        ],
       [0.51111111],
       [0.03703704],
       [0.47407407],
       [0.28888889],
       [0.88888889],
       [0.54814815],
       [0.12592593],
       [0.21481481],
       [0.5037037 ],
       [0.05925926],
       [0.31851852],
       [0.2962963 ],
       [0.24444444],
       [0.47407407],
       [0.02222222],
       [0.75555556],
       [0.03703704],
       [0.53333333],
       [0.37777778],
       [0.77777778],
       [0.5037037 ],
       [0.31851852],
       [0.02962963],
       [0.4962963 ],
       [0.35555556],
       [0.39259259],
       [0.48148148],
       [0.08888889],
       [0.05925926],
       [0.72592593],
       [0.02222222],
       [0.71851852],
       [0.27407407],
       [0.08888889],
       [0.53333333],
       [0.01481481],
       [0.48148148],
       [0.2       ],
       [0.25185185],
       [0.54074074],
       [0.34814815],
       [0.76296296],
       [0.2962963 ],
       [0.51851852],
       [0.48888889],
       [0.25925926],
       [0.48888889],
       [0.74814815],
       [0.        ],
       [0.0962963 ],
       [0.5037037 ],
       [0.21481481],
       [0.07407407],
       [0.8       ],
       [0.42962963],
       [0.16296296],
       [0.54074074],
       [0.32592593],
       [0.52592593],
       [0.99259259],
       [0.04444444],
       [0.42222222],
       [0.14814815],
       [0.54814815],
       [0.52592593],
       [0.48148148],
       [0.41481481],
       [0.41481481],
       [0.34074074],
       [0.2962963 ],
       [0.48148148],
       [0.31111111],
       [0.44444444],
       [0.27407407],
       [0.32592593],
       [0.32592593],
       [0.44444444],
       [0.42222222],
       [0.44444444],
       [0.28148148],
       [0.26666667],
       [0.34074074],
       [0.37037037],
       [0.12592593],
       [0.01481481],
       [0.51111111],
       [0.31851852],
       [0.11851852],
       [0.53333333],
       [0.39259259],
       [0.2962963 ],
       [0.35555556],
       [0.4962963 ],
       [0.68148148],
       [0.32592593],
       [0.07407407],
       [0.51851852],
       [0.39259259],
       [0.32592593],
       [0.54814815],
       [0.07407407],
       [0.54814815],
       [0.6       ],
       [0.11111111],
       [0.34074074],
       [0.43703704],
       [0.        ],
       [0.22222222],
       [0.45185185],
       [0.25925926],
       [0.23703704],
       [0.        ],
       [0.32592593],
       [0.44444444],
       [0.11111111],
       [0.88888889],
       [0.62962963],
       [0.55555556],
       [0.13333333],
       [0.17037037],
       [0.4       ],
       [0.52592593],
       [0.2962963 ],
       [0.41481481],
       [0.98518519],
       [0.23703704],
       [0.54074074],
       [0.74074074],
       [0.76296296],
       [0.20740741],
       [0.42222222],
       [0.0962963 ],
       [0.23703704],
       [0.05185185],
       [0.05925926],
       [0.14074074],
       [0.00740741],
       [0.41481481],
       [0.75555556],
       [0.20740741],
       [0.33333333],
       [0.37777778],
       [0.4962963 ],
       [0.19259259],
       [0.42222222],
       [0.12592593],
       [0.51111111],
       [0.08148148],
       [0.20740741],
       [0.40740741],
       [0.54814815],
       [0.20740741],
       [0.47407407],
       [0.15555556],
       [0.48148148],
       [0.05185185],
       [0.17777778],
       [0.43703704],
       [0.88148148],
       [0.41481481],
       [0.63703704],
       [0.23703704],
       [0.85185185],
       [0.73333333],
       [0.94074074],
       [0.05185185],
       [0.6       ],
       [1.        ],
       [0.2       ],
       [0.31851852],
       [0.20740741],
       [0.68888889],
       [0.37037037],
       [0.46666667],
       [0.6       ],
       [0.94814815],
       [0.48148148],
       [0.56296296],
       [0.95555556],
       [0.64444444],
       [0.33333333],
       [0.28148148],
       [0.82222222],
       [0.87407407],
       [0.42222222],
       [0.48148148],
       [0.97777778],
       [0.2       ],
       [0.68148148],
       [0.52592593],
       [0.71851852],
       [0.47407407],
       [0.31111111],
       [0.48148148],
       [0.4962963 ],
       [0.94814815],
       [0.99259259],
       [0.32592593],
       [0.54074074],
       [0.65925926],
       [0.42222222],
       [0.97037037],
       [0.25925926],
       [0.79259259],
       [0.27407407],
       [0.60740741],
       [0.17777778],
       [0.27407407],
       [0.88148148],
       [0.97037037],
       [0.21481481],
       [0.55555556],
       [0.42222222],
       [0.31111111],
       [0.59259259],
       [0.85925926],
       [0.45925926],
       [0.95555556],
       [0.81481481],
       [0.42222222],
       [0.55555556],
       [0.68888889],
       [0.44444444],
       [0.43703704],
       [0.95555556],
       [0.34074074],
       [0.87407407],
       [0.45185185],
       [0.2       ],
       [0.67407407],
       [0.08148148],
       [0.43703704],
       [0.41481481],
       [0.54074074],
       [0.17037037],
       [0.15555556],
       [0.54074074],
       [0.34074074],
       [0.40740741],
       [0.04444444],
       [0.93333333],
       [0.57777778],
       [0.34814815],
       [0.91111111],
       [0.47407407],
       [0.46666667],
       [0.88148148],
       [0.54814815],
       [0.17777778],
       [0.45925926],
       [0.31111111],
       [0.35555556],
       [0.42962963],
       [0.71851852],
       [0.47407407],
       [0.75555556],
       [0.17037037],
       [0.43703704],
       [0.9037037 ],
       [0.47407407],
       [0.33333333],
       [0.28888889],
       [0.88148148],
       [0.72592593],
       [0.81481481],
       [0.25925926],
       [0.40740741],
       [0.6       ],
       [0.25925926],
       [0.93333333],
       [0.47407407],
       [0.44444444],
       [0.65925926],
       [0.2962963 ],
       [0.12592593],
       [0.33333333],
       [0.91111111],
       [0.4962963 ],
       [0.27407407],
       [0.11111111],
       [0.85925926],
       [0.33333333],
       [0.42222222],
       [0.44444444],
       [0.76296296],
       [0.68148148],
       [0.26666667],
       [0.77037037],
       [0.37037037],
       [0.37037037],
       [0.33333333],
       [0.28888889],
       [0.95555556],
       [0.47407407],
       [0.2962963 ],
       [0.79259259],
       [0.65925926],
       [0.44444444],
       [0.37037037],
       [0.26666667],
       [0.66666667],
       [0.35555556],
       [0.42222222],
       [0.68888889],
       [0.45925926],
       [0.34074074],
       [0.72592593],
       [0.44444444],
       [0.55555556],
       [0.31111111],
       [0.62222222],
       [0.14074074],
       [0.40740741],
       [0.42222222],
       [0.41481481],
       [0.28888889],
       [0.84444444],
       [0.14074074],
       [0.25925926],
       [0.47407407],
       [0.65925926],
       [0.1037037 ],
       [0.23703704],
       [0.54074074],
       [0.41481481],
       [0.08148148],
       [0.22962963],
       [0.5037037 ],
       [0.42962963],
       [0.85185185],
       [0.48148148],
       [0.12592593],
       [0.43703704],
       [0.28148148],
       [0.53333333],
       [0.05925926],
       [0.36296296],
       [0.13333333],
       [0.91851852],
       [0.0962963 ],
       [0.13333333],
       [0.33333333],
       [0.17777778],
       [0.41481481],
       [0.14074074],
       [0.14814815],
       [0.13333333],
       [0.05925926],
       [0.22222222],
       [0.2       ],
       [0.32592593],
       [0.19259259],
       [0.05925926],
       [0.03703704],
       [0.13333333],
       [0.15555556]])

In [22]:
data3['scaled_salary'] = scaled_salary

In [23]:
data3

     Age  EstimatedSalary  Purchased  scaled_salary
0     19            19000          0       0.029630
1     35            20000          0       0.037037
2     26            43000          0       0.207407
3     27            57000          0       0.311111
4     19            76000          0       0.451852
..   ...              ...        ...            ...
395   46            41000          1       0.192593
396   51            23000          1       0.059259
397   50            20000          1       0.037037
398   36            33000          0       0.133333
399   49            36000          1       0.155556

[400 rows x 4 columns]

In [26]:
data3.drop(:,'EstimatedSalary')

SyntaxError: invalid syntax (1216092474.py, line 1)