In [159]:
import pandas as pd

In [160]:
data = pd.read_csv('/content/sample_data/social_ads.csv')

In [161]:
data

     Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [162]:
X = data.loc[:,['Age']]

In [163]:
X

     Age
0     19
1     35
2     26
3     27
4     19
..   ...
395   46
396   51
397   50
398   36
399   49

[400 rows x 1 columns]

In [164]:
y = data.loc[:,['Purchased']]

In [165]:
y

     Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

In [166]:
from sklearn.model_selection import train_test_split as tts

In [167]:
X_train, X_test, y_train, y_test = tts(X,y,test_size=0.2,random_state = 44)

In [168]:
X_train.shape

(320, 1)

In [169]:
X_test.shape

(80, 1)

In [170]:
y_train.shape

(320, 1)

In [171]:
y_test.shape

(80, 1)

In [172]:
from sklearn.linear_model import LogisticRegression

In [173]:
model = LogisticRegression()

In [174]:
model.fit(X_train,y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [175]:
y_pred = model.predict(X_test)

In [176]:
y_pred

array([1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0])

In [177]:
y_test

     Purchased
201          0
258          1
114          0
270          0
7            1
..         ...
159          1
211          1
107          0
236          0
380          0

[80 rows x 1 columns]

In [178]:
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, precision_score, recall_score

In [179]:
acc = accuracy_score(y_test,y_pred)

In [180]:
acc

0.7875

In [181]:
f1_s = f1_score(y_test,y_pred)

In [182]:
f1_s

0.7536231884057971

In [183]:
cm = confusion_matrix(y_test,y_pred)

In [184]:
cm

array([[37,  4],
       [13, 26]])

In [185]:
ps = precision_score(y_test,y_pred)

In [186]:
ps

0.8666666666666667

In [187]:
rs = recall_score(y_test,y_pred)

In [188]:
rs

0.6666666666666666