In [41]:
import pandas as pd

In [42]:
data = pd.read_csv("E:\Machine_Learning_Journey\Machine_Learning_Journey\data_sets\height-weight.csv")

In [43]:
data.head()

   Weight  Height
0      45     120
1      58     135
2      48     123
3      60     145
4      70     160

In [44]:
data['Weight'].max()

105

In [45]:
data.describe()

           Weight      Height
count   23.000000   23.000000
mean    73.826087  158.391304
std     17.872407   19.511626
min     45.000000  120.000000
25%     59.000000  142.500000
50%     78.000000  162.000000
75%     86.000000  175.000000
max    105.000000  183.000000

In [46]:
from sklearn.preprocessing import StandardScaler

In [47]:
ss = StandardScaler()

In [48]:
data_copy = data.copy()

In [49]:
data_copy.head()

   Weight  Height
0      45     120
1      58     135
2      48     123
3      60     145
4      70     160

In [50]:
data_copy_scaler = ss.fit_transform(data_copy)

In [51]:
data_copy_scaler

array([[-1.64913128, -2.01183323],
       [-0.90540541, -1.22578288],
       [-1.47750223, -1.85462316],
       [-0.79098604, -0.7017493 ],
       [-0.21888922,  0.08430105],
       [ 0.23878824,  0.18910777],
       [ 0.3532076 ,  0.24151112],
       [ 0.92530443,  0.87035141],
       [ 1.21135284,  1.23717491],
       [ 0.23878824,  0.60833462],
       [ 0.46762697,  0.92275477],
       [ 1.21135284,  1.23717491],
       [ 1.78344966,  0.87035141],
       [ 1.49740125,  1.28957827],
       [ 0.63925602,  0.60833462],
       [ 0.23878824,  0.97515812],
       [-1.36308287, -0.96376609],
       [-0.50493763,  0.0318977 ],
       [ 0.12436887, -0.43973252],
       [ 0.75367538,  0.45112455],
       [-1.64913128, -1.54020302],
       [-1.01982477, -0.96376609],
       [-0.10446985,  0.08430105]])

In [52]:
data_copy[:] = data_copy_scaler

In [53]:
data_copy.head()

     Weight    Height
0 -1.649131 -2.011833
1 -0.905405 -1.225783
2 -1.477502 -1.854623
3 -0.790986 -0.701749
4 -0.218889  0.084301

In [54]:
from sklearn.model_selection import train_test_split as tts

In [55]:
X = data_copy.loc[:,['Weight']]

In [56]:
X.head()

     Weight
0 -1.649131
1 -0.905405
2 -1.477502
3 -0.790986
4 -0.218889

In [57]:
y = data_copy.loc[:,['Height']]

In [58]:
y.head()

     Height
0 -2.011833
1 -1.225783
2 -1.854623
3 -0.701749
4  0.084301

In [59]:
X_train, X_test, y_train, y_test = tts(X,y, train_size = 0.8, random_state = 44)

In [60]:
len(X_train)

18

In [61]:
X_test.shape

(5, 1)

In [62]:
y_train.shape

(18, 1)

In [63]:
y_test.shape

(5, 1)

In [65]:
data_copy.shape

(23, 2)

In [66]:
from sklearn.linear_model import LinearRegression

In [67]:
model = LinearRegression()

In [68]:
model.fit(X_train,y_train)

LinearRegression()

In [69]:
y_pred = model.predict(X_test)

In [70]:
y_pred

array([[-0.06102221],
       [-1.26768411],
       [ 0.24064326],
       [-0.76490832],
       [-0.16157737]])

In [71]:
y_test

      Height
22  0.084301
2  -1.854623
5   0.189108
1  -1.225783
4   0.084301

In [74]:
from sklearn.metrics import mean_squared_error as mse

In [75]:
mse(y_test,y_pred)

0.1282267533066141

In [77]:
X1 = data.loc[:,['Weight']]

In [79]:
y1 = data.loc[:,['Height']]

In [81]:
X1_train,X1_test, y1_train, y1_test = tts(X1,y1, train_size = 0.8, random_state= 44)

In [82]:
model.fit(X1_train, y1_train)

LinearRegression()

In [83]:
y1_pred = model.predict(X1_test)

In [84]:
y1_pred

array([[157.2268329 ],
       [134.20040938],
       [162.98343878],
       [143.79475251],
       [155.30796427]])

In [85]:
y1_test

    Height
22     160
2      123
5      162
1      135
4      160

In [86]:
mse(y1_test,y1_pred)

46.69392977310565