In [7]:
import pandas as pd
from sklearn.preprocessing import MaxAbsScaler

In [8]:
data = pd.read_csv("E:\Machine_Learning_Journey\Machine_Learning_Journey\data_sets\social_ads.csv")

In [9]:
data

     Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [10]:
data2 = data.copy()

In [11]:
data2['EstimatedSalary'].max()

150000

In [12]:
data2['EstimatedSalary'].min()

15000

In [13]:
mas = MaxAbsScaler()

In [16]:
scaled_salary = mas.fit_transform(data2[['EstimatedSalary']])

In [19]:
scaled_salary

array([[0.12666667],
       [0.13333333],
       [0.28666667],
       [0.38      ],
       [0.50666667],
       [0.38666667],
       [0.56      ],
       [1.        ],
       [0.22      ],
       [0.43333333],
       [0.53333333],
       [0.34666667],
       [0.57333333],
       [0.12      ],
       [0.54666667],
       [0.53333333],
       [0.16666667],
       [0.17333333],
       [0.18666667],
       [0.19333333],
       [0.14666667],
       [0.32666667],
       [0.27333333],
       [0.14666667],
       [0.15333333],
       [0.13333333],
       [0.18666667],
       [0.2       ],
       [0.28666667],
       [0.12      ],
       [0.49333333],
       [0.91333333],
       [0.10666667],
       [0.29333333],
       [0.6       ],
       [0.18      ],
       [0.18666667],
       [0.32666667],
       [0.48      ],
       [0.20666667],
       [0.11333333],
       [0.34      ],
       [0.72      ],
       [0.1       ],
       [0.56      ],
       [0.13333333],
       [0.52666667],
       [0.36      ],
       [0.9       ],
       [0.59333333],
       [0.21333333],
       [0.29333333],
       [0.55333333],
       [0.15333333],
       [0.38666667],
       [0.36666667],
       [0.32      ],
       [0.52666667],
       [0.12      ],
       [0.78      ],
       [0.13333333],
       [0.58      ],
       [0.44      ],
       [0.8       ],
       [0.55333333],
       [0.38666667],
       [0.12666667],
       [0.54666667],
       [0.42      ],
       [0.45333333],
       [0.53333333],
       [0.18      ],
       [0.15333333],
       [0.75333333],
       [0.12      ],
       [0.74666667],
       [0.34666667],
       [0.18      ],
       [0.58      ],
       [0.11333333],
       [0.53333333],
       [0.28      ],
       [0.32666667],
       [0.58666667],
       [0.41333333],
       [0.78666667],
       [0.36666667],
       [0.56666667],
       [0.54      ],
       [0.33333333],
       [0.54      ],
       [0.77333333],
       [0.1       ],
       [0.18666667],
       [0.55333333],
       [0.29333333],
       [0.16666667],
       [0.82      ],
       [0.48666667],
       [0.24666667],
       [0.58666667],
       [0.39333333],
       [0.57333333],
       [0.99333333],
       [0.14      ],
       [0.48      ],
       [0.23333333],
       [0.59333333],
       [0.57333333],
       [0.53333333],
       [0.47333333],
       [0.47333333],
       [0.40666667],
       [0.36666667],
       [0.53333333],
       [0.38      ],
       [0.5       ],
       [0.34666667],
       [0.39333333],
       [0.39333333],
       [0.5       ],
       [0.48      ],
       [0.5       ],
       [0.35333333],
       [0.34      ],
       [0.40666667],
       [0.43333333],
       [0.21333333],
       [0.11333333],
       [0.56      ],
       [0.38666667],
       [0.20666667],
       [0.58      ],
       [0.45333333],
       [0.36666667],
       [0.42      ],
       [0.54666667],
       [0.71333333],
       [0.39333333],
       [0.16666667],
       [0.56666667],
       [0.45333333],
       [0.39333333],
       [0.59333333],
       [0.16666667],
       [0.59333333],
       [0.64      ],
       [0.2       ],
       [0.40666667],
       [0.49333333],
       [0.1       ],
       [0.3       ],
       [0.50666667],
       [0.33333333],
       [0.31333333],
       [0.1       ],
       [0.39333333],
       [0.5       ],
       [0.2       ],
       [0.9       ],
       [0.66666667],
       [0.6       ],
       [0.22      ],
       [0.25333333],
       [0.46      ],
       [0.57333333],
       [0.36666667],
       [0.47333333],
       [0.98666667],
       [0.31333333],
       [0.58666667],
       [0.76666667],
       [0.78666667],
       [0.28666667],
       [0.48      ],
       [0.18666667],
       [0.31333333],
       [0.14666667],
       [0.15333333],
       [0.22666667],
       [0.10666667],
       [0.47333333],
       [0.78      ],
       [0.28666667],
       [0.4       ],
       [0.44      ],
       [0.54666667],
       [0.27333333],
       [0.48      ],
       [0.21333333],
       [0.56      ],
       [0.17333333],
       [0.28666667],
       [0.46666667],
       [0.59333333],
       [0.28666667],
       [0.52666667],
       [0.24      ],
       [0.53333333],
       [0.14666667],
       [0.26      ],
       [0.49333333],
       [0.89333333],
       [0.47333333],
       [0.67333333],
       [0.31333333],
       [0.86666667],
       [0.76      ],
       [0.94666667],
       [0.14666667],
       [0.64      ],
       [1.        ],
       [0.28      ],
       [0.38666667],
       [0.28666667],
       [0.72      ],
       [0.43333333],
       [0.52      ],
       [0.64      ],
       [0.95333333],
       [0.53333333],
       [0.60666667],
       [0.96      ],
       [0.68      ],
       [0.4       ],
       [0.35333333],
       [0.84      ],
       [0.88666667],
       [0.48      ],
       [0.53333333],
       [0.98      ],
       [0.28      ],
       [0.71333333],
       [0.57333333],
       [0.74666667],
       [0.52666667],
       [0.38      ],
       [0.53333333],
       [0.54666667],
       [0.95333333],
       [0.99333333],
       [0.39333333],
       [0.58666667],
       [0.69333333],
       [0.48      ],
       [0.97333333],
       [0.33333333],
       [0.81333333],
       [0.34666667],
       [0.64666667],
       [0.26      ],
       [0.34666667],
       [0.89333333],
       [0.97333333],
       [0.29333333],
       [0.6       ],
       [0.48      ],
       [0.38      ],
       [0.63333333],
       [0.87333333],
       [0.51333333],
       [0.96      ],
       [0.83333333],
       [0.48      ],
       [0.6       ],
       [0.72      ],
       [0.5       ],
       [0.49333333],
       [0.96      ],
       [0.40666667],
       [0.88666667],
       [0.50666667],
       [0.28      ],
       [0.70666667],
       [0.17333333],
       [0.49333333],
       [0.47333333],
       [0.58666667],
       [0.25333333],
       [0.24      ],
       [0.58666667],
       [0.40666667],
       [0.46666667],
       [0.14      ],
       [0.94      ],
       [0.62      ],
       [0.41333333],
       [0.92      ],
       [0.52666667],
       [0.52      ],
       [0.89333333],
       [0.59333333],
       [0.26      ],
       [0.51333333],
       [0.38      ],
       [0.42      ],
       [0.48666667],
       [0.74666667],
       [0.52666667],
       [0.78      ],
       [0.25333333],
       [0.49333333],
       [0.91333333],
       [0.52666667],
       [0.4       ],
       [0.36      ],
       [0.89333333],
       [0.75333333],
       [0.83333333],
       [0.33333333],
       [0.46666667],
       [0.64      ],
       [0.33333333],
       [0.94      ],
       [0.52666667],
       [0.5       ],
       [0.69333333],
       [0.36666667],
       [0.21333333],
       [0.4       ],
       [0.92      ],
       [0.54666667],
       [0.34666667],
       [0.2       ],
       [0.87333333],
       [0.4       ],
       [0.48      ],
       [0.5       ],
       [0.78666667],
       [0.71333333],
       [0.34      ],
       [0.79333333],
       [0.43333333],
       [0.43333333],
       [0.4       ],
       [0.36      ],
       [0.96      ],
       [0.52666667],
       [0.36666667],
       [0.81333333],
       [0.69333333],
       [0.5       ],
       [0.43333333],
       [0.34      ],
       [0.7       ],
       [0.42      ],
       [0.48      ],
       [0.72      ],
       [0.51333333],
       [0.40666667],
       [0.75333333],
       [0.5       ],
       [0.6       ],
       [0.38      ],
       [0.66      ],
       [0.22666667],
       [0.46666667],
       [0.48      ],
       [0.47333333],
       [0.36      ],
       [0.86      ],
       [0.22666667],
       [0.33333333],
       [0.52666667],
       [0.69333333],
       [0.19333333],
       [0.31333333],
       [0.58666667],
       [0.47333333],
       [0.17333333],
       [0.30666667],
       [0.55333333],
       [0.48666667],
       [0.86666667],
       [0.53333333],
       [0.21333333],
       [0.49333333],
       [0.35333333],
       [0.58      ],
       [0.15333333],
       [0.42666667],
       [0.22      ],
       [0.92666667],
       [0.18666667],
       [0.22      ],
       [0.4       ],
       [0.26      ],
       [0.47333333],
       [0.22666667],
       [0.23333333],
       [0.22      ],
       [0.15333333],
       [0.3       ],
       [0.28      ],
       [0.39333333],
       [0.27333333],
       [0.15333333],
       [0.13333333],
       [0.22      ],
       [0.24      ]])

In [20]:
data2

     Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [21]:
data2['scaled_salary'] = scaled_salary

In [22]:
data2

     Age  EstimatedSalary  Purchased  scaled_salary
0     19            19000          0       0.126667
1     35            20000          0       0.133333
2     26            43000          0       0.286667
3     27            57000          0       0.380000
4     19            76000          0       0.506667
..   ...              ...        ...            ...
395   46            41000          1       0.273333
396   51            23000          1       0.153333
397   50            20000          1       0.133333
398   36            33000          0       0.220000
399   49            36000          1       0.240000

[400 rows x 4 columns]

In [23]:
data2.describe()

              Age  EstimatedSalary   Purchased  scaled_salary
count  400.000000       400.000000  400.000000     400.000000
mean    37.655000     69742.500000    0.357500       0.464950
std     10.482877     34096.960282    0.479864       0.227313
min     18.000000     15000.000000    0.000000       0.100000
25%     29.750000     43000.000000    0.000000       0.286667
50%     37.000000     70000.000000    0.000000       0.466667
75%     46.000000     88000.000000    1.000000       0.586667
max     60.000000    150000.000000    1.000000       1.000000